blank_issues_enabled: true
contact_links: 
  - name: ğŸ’¬ Discussions
    url: https://github.com/sotashimozono/sotashimozono.github.io/discussions
    about: è³ªå•ã‚„ä¸€èˆ¬çš„ãªè­°è«–ã¯Discussionsã‚’ã”åˆ©ç”¨ãã ã•ã„